### ISSUE TITLE
双拼输入法中寻找配对组合方法的疑问

### ISSUE THREAD

**Issue by warnersiny** [mobyw/TypingCodingResearch#1]
作者您好，我看了您的这个项目，写的十分清晰，程序也运行良好，但有一个地方我不太明白，就是使用双拼输入法进行编码改良时，您提到了一个相似性原理(根据相似性原则找到所有不会重复的配对组合)，这句话我不太明白是什么，所以第二张声母和韵母的匹配图就没看懂，您能讲解一下这部分吗？十分感谢！

**Comment by mobyw** [comment]
部分韵母在和声母组合时是互斥的，例如能与 `ia` 组合的声母一定不能与 `ua` 组合，反之亦然。
声韵母组合图即为合法的组合。

**Comment by mobyw** [comment]
原文描述不准确，此处即为通过组合图找出互斥的韵母组合
